[package]
name = "transferia-connector-mysql"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
bytes.workspace = true
chrono.workspace = true
futures-util.workspace = true
getrandom.workspace = true
mysql_async = { workspace = true, features = ["binlog"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlparser = "0.59"
tokio.workspace = true
tokio-util.workspace = true
transferia-connector-support = { path = "../transferia-connector-support" }
transferia-core = { path = "../transferia-core" }
transferia-delivery-contracts = { path = "../transferia-delivery-contracts" }
transferia-registry = { path = "../transferia-registry" }

[dev-dependencies]
serde_yaml.workspace = true
testcontainers.workspace = true

[lints]
workspace = true
