delivery_id: postgres-ytsaurus-demo
delivery_type: batch
durable_storage: { type: local_file, path: .transferia-state }
source:
  postgres:
    host: localhost
    port: 5432
    database: postgres
    username: postgres
    password: postgres
    trusted_plaintext: true
    tables:
      - name: events
sink:
  ytsaurus:
    host: localhost
    port: 8000
    trusted_plaintext: true
    replace_tables: false
    format: arrow
    tables:
      - dataset: events
        path: //tmp/events_copy
