delivery_id: ytsaurus-clickhouse-demo
delivery_name: Demo delivery
delivery_type: batch
durable_storage: { type: local_file, path: .transferia-state }
source:
  ytsaurus:
    installation:
      type: on_premise
      host: localhost
      port: 8000
      trusted_plaintext: true
    batch_rows: 65536
    tables:
      - path: //tmp/events
sink:
  clickhouse:
    installation:
      type: on_premise
      hosts: [localhost]
      port: 9440
      trusted_plaintext: true
    database: default
    username: default
