delivery_id: postgres-ytsaurus-demo
delivery_name: Demo delivery
delivery_type: batch
durable_storage: { type: local_file, path: .transferia-state }
source:
  postgres:
    installation:
      type: on_premise
      host: localhost
      port: 5432
      trusted_plaintext: true
    database: postgres
    username: postgres
    password: postgres
    tables:
      - name: events
sink:
  ytsaurus:
    installation:
      type: on_premise
      host: localhost
      port: 8000
      trusted_plaintext: true
    replace_tables: false
    format: arrow
    tables:
      - dataset: events
        path: //tmp/events_copy
