[package]
name = "transferia-pipeline"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
transferia-core = { path = "../transferia-core" }
transferia-delivery-contracts = { path = "../transferia-delivery-contracts" }

[lints]
workspace = true

[dev-dependencies]
bytes.workspace = true
futures-util.workspace = true
