import { mkdir, readFile, writeFile } from "node:fs/promises";
import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import addFormats from "ajv-formats";
import prettier from "prettier";

const schemaPath = new URL(
  "../../crates/transferia-server-contracts/contracts/server-api.schema.json",
  import.meta.url,
);
const outputPath = new URL("../src/generated/apiContract.ts", import.meta.url);
const validatorsPath = new URL(
  "../src/generated/apiValidators.generated.js",
  import.meta.url,
);
const validatorTypesPath = new URL(
  "../src/generated/apiValidators.generated.d.ts",
  import.meta.url,
);
const routesPath = new URL(
  "../../crates/transferia-server-contracts/contracts/server-api.routes.json",
  import.meta.url,
);
const contract = JSON.parse(await readFile(schemaPath, "utf8"));
const routes = JSON.parse(await readFile(routesPath, "utf8"));
const checkOnly = process.argv.includes("--check");

assertSupportedContract(contract);

function referenceName(reference) {
  const prefix = "#/$defs/";
  if (!reference.startsWith(prefix))
    throw new Error(`Unsupported $ref: ${reference}`);
  return reference.slice(prefix.length);
}

function literal(value) {
  return JSON.stringify(value);
}

function typeOf(schema, propertyName) {
  if (schema === true) return "JsonValue";
  if (schema === false) return "never";
  if (typeof schema["x-typescript-type"] === "string") {
    return schema["x-typescript-type"];
  }
  if (schema.$ref) return referenceName(schema.$ref);
  if (schema.const !== undefined) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ");
  const choices = schema.oneOf ?? schema.anyOf;
  if (choices) {
    const effective = schema["x-omit-none"]
      ? choices.filter((choice) => choice.type !== "null")
      : choices;
    return effective.map((choice) => typeOf(choice, propertyName)).join(" | ");
  }
  if (Array.isArray(schema.type)) {
    const types = schema["x-omit-none"]
      ? schema.type.filter((type) => type !== "null")
      : schema.type;
    return types
      .map((type) => typeOf({ ...schema, type }, propertyName))
      .join(" | ");
  }
  switch (schema.type) {
    case "object": {
      const required = new Set(schema.required ?? []);
      const properties = Object.entries(schema.properties ?? {}).map(
        ([name, property]) =>
          `  ${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${typeOf(property, name)};`,
      );
      if (
        schema.additionalProperties &&
        schema.additionalProperties !== false
      ) {
        properties.push(
          `  [key: string]: ${schema.additionalProperties === true ? "JsonValue" : typeOf(schema.additionalProperties)};`,
        );
      }
      return `{\n${properties.join("\n")}\n}`;
    }
    case "array":
      return `Array<${typeOf(schema.items ?? true, propertyName)}>`;
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case undefined:
      throw new Error(
        `Schema${propertyName === undefined ? "" : ` for ${propertyName}`} has no supported type, reference, enum, or union`,
      );
    default:
      throw new Error(`Unsupported JSON Schema type: ${schema.type}`);
  }
}

const definitions = Object.entries(contract.$defs ?? {}).map(
  ([name, schema]) => `export type ${name} = ${typeOf(schema)};`,
);
const roots = Object.entries(contract.properties ?? {}).map(
  ([name, schema]) => `  ${JSON.stringify(name)}: ${typeOf(schema, name)};`,
);
const routeEntries = routes.map(
  (route) =>
    `  ${JSON.stringify(route.name)}: ${JSON.stringify({ method: route.method, path: route.path, body: route.body, query: route.query, response: route.response })},`,
);
const routeContracts = routes.map(
  (route) =>
    `  ${JSON.stringify(route.name)}: ApiContract[${JSON.stringify(route.response)}];`,
);
const routeBodies = routes.map(
  (route) =>
    `  ${JSON.stringify(route.name)}: ${route.body === null ? "undefined" : `ApiContract[${JSON.stringify(route.body)}]`};`,
);
const routeQueries = routes.map(
  (route) =>
    `  ${JSON.stringify(route.name)}: ${route.query === null ? "undefined" : `ApiContract[${JSON.stringify(route.query)}]`};`,
);
const routeParameters = routes.map((route) => {
  const names = [...route.path.matchAll(/\{([^}]+)\}/g)].map(
    (match) => match[1],
  );
  const type =
    names.length === 0
      ? "Record<string, never>"
      : `{ ${names.map((name) => `${JSON.stringify(name)}: string`).join("; ")} }`;
  return `  ${JSON.stringify(route.name)}: ${type};`;
});
const output = `// Generated by web/scripts/generate-api.mjs from Rust JsonSchema DTOs.\n// Do not edit by hand.\n\nimport type { JsonObject, JsonSchema, JsonValue } from "../json";\n\n${definitions.join("\n\n")}\n\nexport interface ApiContract {\n${roots.join("\n")}\n}\n\nexport type ApiContractName = keyof ApiContract;\n\nexport const API_ROUTES = {\n${routeEntries.join("\n")}\n} as const satisfies Record<string, { method: string; path: string; body: ApiContractName | null; query: ApiContractName | null; response: ApiContractName }>;\nexport interface ApiRouteContract {\n${routeContracts.join("\n")}\n}\nexport interface ApiRouteBody {\n${routeBodies.join("\n")}\n}\nexport interface ApiRouteQuery {\n${routeQueries.join("\n")}\n}\nexport interface ApiRouteParameters {\n${routeParameters.join("\n")}\n}\nexport type ApiRouteName = keyof ApiRouteContract;\n`;
await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
const formatted = await prettier.format(output, { parser: "typescript" });
const current = await readFile(outputPath, "utf8").catch((error) => {
  if (error.code === "ENOENT") return undefined;
  throw error;
});
if (current !== formatted) {
  if (checkOnly)
    throw new Error(
      "Generated API types are stale. Run `npm run update:api` and commit the result.",
    );
  await writeFile(outputPath, formatted);
}

const validationContract = withoutOmittedNulls(contract);
const ajv = new Ajv2020({
  allErrors: true,
  strict: true,
  code: { source: true, esm: true },
});
addFormats(ajv);
ajv.addKeyword({ keyword: "x-omit-none", schemaType: "boolean" });
ajv.addKeyword({ keyword: "x-typescript-type", schemaType: "string" });
for (const format of ["int64", "uint", "uint32", "uint64"])
  ajv.addFormat(format, true);
const validatorExports = {};
for (const [name, schema] of Object.entries(validationContract.properties)) {
  ajv.addSchema(
    {
      $schema: validationContract.$schema,
      $id: `urn:transferia:server-api:${name}`,
      $defs: validationContract.$defs,
      ...schema,
    },
    name,
  );
  validatorExports[name] = name;
}
const validatorSource = `${standaloneCode(ajv, validatorExports)}\n`;
const validatorTypes = `// Generated by web/scripts/generate-api.mjs. Do not edit.\nimport type { ValidateFunction } from "ajv";\n${Object.keys(validatorExports)
  .map((name) => `export const ${name}: ValidateFunction;`)
  .join("\n")}\n`;
await writeGenerated(validatorsPath, validatorSource);
await writeGenerated(validatorTypesPath, validatorTypes);

async function writeGenerated(path, contents) {
  const existing = await readFile(path, "utf8").catch((error) => {
    if (error.code === "ENOENT") return undefined;
    throw error;
  });
  if (existing === contents) return;
  if (checkOnly)
    throw new Error(
      "Generated API validators are stale. Run `npm run update:api` and commit the result.",
    );
  await writeFile(path, contents);
}

function withoutOmittedNulls(value) {
  if (Array.isArray(value)) return value.map(withoutOmittedNulls);
  if (value === null || typeof value !== "object") return value;
  const result = Object.fromEntries(
    Object.entries(value).map(([key, child]) => [key, withoutOmittedNulls(child)]),
  );
  if (result["x-omit-none"] === true) {
    if (Array.isArray(result.type))
      result.type = result.type.filter((type) => type !== "null");
    for (const key of ["oneOf", "anyOf"]) {
      if (Array.isArray(result[key]))
        result[key] = result[key].filter(
          (choice) =>
            choice === null ||
            typeof choice !== "object" ||
            choice.type !== "null",
        );
    }
  }
  return result;
}

function assertSupportedContract(root) {
  const supported = new Set([
    "$ref",
    "type",
    "const",
    "enum",
    "oneOf",
    "anyOf",
    "properties",
    "required",
    "additionalProperties",
    "items",
    "pattern",
    "minimum",
    "maximum",
    "format",
    "default",
    "title",
    "description",
    "x-omit-none",
    "x-typescript-type",
  ]);
  const visit = (schema, path) => {
    if (schema === true || schema === false) return;
    if (schema === null || typeof schema !== "object" || Array.isArray(schema))
      throw new Error(`${path}: expected a JSON Schema object`);
    const unknown = Object.keys(schema).filter((key) => !supported.has(key));
    if (unknown.length > 0)
      throw new Error(
        `${path}: API generator does not support keywords ${unknown.join(", ")}`,
      );
    if (schema.$ref !== undefined && Object.keys(schema).length !== 1)
      throw new Error(`${path}: sibling keywords next to $ref are unsupported`);
    for (const [name, child] of Object.entries(schema.properties ?? {}))
      visit(child, `${path}/properties/${name}`);
    for (const [index, child] of (schema.oneOf ?? []).entries())
      visit(child, `${path}/oneOf/${index}`);
    for (const [index, child] of (schema.anyOf ?? []).entries())
      visit(child, `${path}/anyOf/${index}`);
    if (schema.items !== undefined) visit(schema.items, `${path}/items`);
    if (
      schema.additionalProperties !== undefined &&
      typeof schema.additionalProperties !== "boolean"
    )
      visit(schema.additionalProperties, `${path}/additionalProperties`);
  };
  for (const [name, schema] of Object.entries(root.$defs ?? {}))
    visit(schema, `#/$defs/${name}`);
  for (const [name, schema] of Object.entries(root.properties ?? {}))
    visit(schema, `#/properties/${name}`);
}
