import { mkdir, readFile, writeFile } from "node:fs/promises";
import prettier from "prettier";

const schemaPath = new URL("../../contracts/server-api.schema.json", import.meta.url);
const outputPath = new URL("../src/generated/apiContract.ts", import.meta.url);
const contract = JSON.parse(await readFile(schemaPath, "utf8"));

function referenceName(reference) {
  const prefix = "#/$defs/";
  if (!reference.startsWith(prefix)) throw new Error(`Unsupported $ref: ${reference}`);
  return reference.slice(prefix.length);
}

function literal(value) {
  return JSON.stringify(value);
}

function typeOf(schema, propertyName) {
  if (schema === true) return "JsonValue";
  if (schema === false) return "never";
  if (typeof schema["x-typescript-type"] === "string") {
    return schema["x-typescript-type"];
  }
  if (schema.$ref) return referenceName(schema.$ref);
  if (schema.const !== undefined) return literal(schema.const);
  if (schema.enum) return schema.enum.map(literal).join(" | ");
  const choices = schema.oneOf ?? schema.anyOf;
  if (choices) {
    const effective = schema["x-omit-none"]
      ? choices.filter((choice) => choice.type !== "null")
      : choices;
    return effective.map((choice) => typeOf(choice, propertyName)).join(" | ");
  }
  if (Array.isArray(schema.type)) {
    const types = schema["x-omit-none"]
      ? schema.type.filter((type) => type !== "null")
      : schema.type;
    return types
      .map((type) => typeOf({ ...schema, type }, propertyName))
      .join(" | ");
  }
  switch (schema.type) {
    case "object": {
      const required = new Set(schema.required ?? []);
      const properties = Object.entries(schema.properties ?? {}).map(
        ([name, property]) =>
          `  ${JSON.stringify(name)}${required.has(name) ? "" : "?"}: ${typeOf(property, name)};`,
      );
      if (schema.additionalProperties && schema.additionalProperties !== false) {
        properties.push(
          `  [key: string]: ${schema.additionalProperties === true ? "JsonValue" : typeOf(schema.additionalProperties)};`,
        );
      }
      return `{\n${properties.join("\n")}\n}`;
    }
    case "array":
      return `Array<${typeOf(schema.items ?? true, propertyName)}>`;
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case undefined:
      return "JsonValue";
    default:
      throw new Error(`Unsupported JSON Schema type: ${schema.type}`);
  }
}

const definitions = Object.entries(contract.$defs ?? {}).map(
  ([name, schema]) => `export type ${name} = ${typeOf(schema)};`,
);
const roots = Object.entries(contract.properties ?? {}).map(
  ([name, schema]) => `  ${JSON.stringify(name)}: ${typeOf(schema, name)};`,
);
const output = `// Generated by web/scripts/generate-api.mjs from Rust JsonSchema DTOs.\n// Do not edit by hand.\n\nimport type { JsonObject, JsonSchema, JsonValue } from "../json";\n\n${definitions.join("\n\n")}\n\nexport interface ApiContract {\n${roots.join("\n")}\n}\n\nexport type ApiContractName = keyof ApiContract;\n`;
await mkdir(new URL("../src/generated/", import.meta.url), { recursive: true });
await writeFile(outputPath, await prettier.format(output, { parser: "typescript" }));
