[package]
name = "transferia-composition"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "transferia"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
mimalloc.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing-subscriber.workspace = true
transferia-control-plane = { path = "../transferia-control-plane", features = ["datafusion"] }
transferia-delivery = { path = "../transferia-delivery" }
transferia-providers = { path = "../transferia-providers" }
transferia-runtime-local = { path = "../transferia-runtime-local" }

[lints]
workspace = true
