[package]
name = "transferia-connector-ydb"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
futures-util.workspace = true
http.workspace = true
murmur3.workspace = true
prost.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
shellexpand.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tonic = { workspace = true, features = ["transport", "tls-aws-lc", "tls-native-roots"] }
tracing.workspace = true
transferia-connector-support = { path = "../transferia-connector-support" }
transferia-core = { path = "../transferia-core" }
transferia-delivery-contracts = { path = "../transferia-delivery-contracts" }
transferia-registry = { path = "../transferia-registry" }
uuid.workspace = true
ydb-grpc.workspace = true

[dev-dependencies]
serde_yaml.workspace = true
testcontainers.workspace = true
transferia-test-support = { path = "../transferia-test-support" }

[lints]
workspace = true
