use serde::Serialize;

#[derive(Clone, Copy, Debug, Serialize)]
pub struct ApiRoute {
    pub name: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub body: Option<&'static str>,
    pub query: Option<&'static str>,
    pub response: &'static str,
}

macro_rules! routes {
    ($(($constant:ident, $name:literal, $method:literal, $path:literal, $body:expr, $query:expr, $response:literal)),+ $(,)?) => {
        $(pub const $constant: ApiRoute = ApiRoute { name: $name, method: $method, path: $path, body: $body, query: $query, response: $response };)+
        pub const API_ROUTES: &[ApiRoute] = &[$($constant),+];
    };
}

routes![
    (
        HEALTH,
        "health",
        "GET",
        "/api/v1/health",
        None,
        None,
        "health_response"
    ),
    (
        CATALOG,
        "catalog",
        "GET",
        "/api/v1/catalog",
        None,
        None,
        "catalog_response"
    ),
    (
        OPTIONS,
        "options",
        "POST",
        "/api/v1/options/{key}",
        Some("dynamic_options_request"),
        None,
        "dynamic_options_response"
    ),
    (
        CHECK_CONNECTION,
        "check_connection",
        "POST",
        "/api/v1/check-connection",
        Some("connection_check_request"),
        None,
        "connection_check_response"
    ),
    (
        PREVIEW_MESSAGE,
        "preview_message",
        "POST",
        "/api/v1/preview-message",
        Some("message_preview_request"),
        None,
        "message_preview_response"
    ),
    (
        SQL_PLAYGROUND,
        "sql_playground",
        "POST",
        "/api/v1/playground/sql",
        Some("sql_playground_request"),
        None,
        "sql_playground_response"
    ),
    (
        SPEEDTEST_ESTIMATE,
        "speedtest_estimate",
        "POST",
        "/api/v1/speedtest/estimate",
        Some("speedtest_estimate_request"),
        None,
        "speedtest_estimate_response"
    ),
    (
        SPEEDTEST_TUNE,
        "speedtest_tune",
        "POST",
        "/api/v1/speedtest/tune",
        Some("speedtest_tune_request"),
        None,
        "speedtest_tune_response"
    ),
    (
        RENDER_YAML,
        "render_yaml",
        "POST",
        "/api/v1/config/yaml",
        Some("config_request"),
        None,
        "yaml_response"
    ),
    (
        PARSE_YAML,
        "parse_yaml",
        "POST",
        "/api/v1/config/from-yaml",
        Some("yaml_request"),
        None,
        "config_response"
    ),
    (
        DISCOVER,
        "discover",
        "POST",
        "/api/v1/discover",
        Some("config_request"),
        None,
        "discovery_response"
    ),
    (
        LIST_DELIVERIES,
        "list_deliveries",
        "GET",
        "/api/v1/deliveries",
        None,
        None,
        "delivery_list_response"
    ),
    (
        CREATE_DELIVERY,
        "create_delivery",
        "POST",
        "/api/v1/deliveries",
        Some("create_draft_request"),
        None,
        "delivery_response"
    ),
    (
        GET_DELIVERY,
        "get_delivery",
        "GET",
        "/api/v1/deliveries/{id}",
        None,
        None,
        "delivery_response"
    ),
    (
        UPDATE_DELIVERY,
        "update_delivery",
        "PUT",
        "/api/v1/deliveries/{id}",
        Some("update_draft_request"),
        None,
        "delivery_response"
    ),
    (
        DELETE_DELIVERY,
        "delete_delivery",
        "DELETE",
        "/api/v1/deliveries/{id}",
        Some("revision_request"),
        None,
        "delivery_response"
    ),
    (
        VALIDATE,
        "validate",
        "POST",
        "/api/v1/deliveries/{id}/validate",
        Some("revision_request"),
        None,
        "validation_response"
    ),
    (
        ACTIVATE,
        "activate",
        "POST",
        "/api/v1/deliveries/{id}/activate",
        Some("revision_request"),
        None,
        "delivery_response"
    ),
    (
        STOP,
        "stop",
        "POST",
        "/api/v1/deliveries/{id}/stop",
        Some("stop_request"),
        None,
        "delivery_response"
    ),
    (
        WORKER_LOGS,
        "worker_logs",
        "GET",
        "/api/v1/deliveries/{id}/logs",
        None,
        None,
        "worker_logs_response"
    ),
    (
        WORKER_LOG,
        "worker_log",
        "GET",
        "/api/v1/deliveries/{id}/logs/{worker_id}",
        None,
        Some("worker_log_read_query"),
        "worker_log_response"
    ),
];
