[package]
name = "transferia-provider-ytsaurus"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
http.workspace = true
hyper.workspace = true
hyper-util.workspace = true
itoa.workspace = true
reqwest.workspace = true
ryu.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
shellexpand.workspace = true
time.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
transferia-core = { path = "../transferia-core" }
transferia-delivery-contracts = { path = "../transferia-delivery-contracts" }
transferia-provider-support = { path = "../transferia-provider-support" }
transferia-registry = { path = "../transferia-registry" }

[dev-dependencies]
serde_yaml.workspace = true
testcontainers.workspace = true
transferia-test-support = { path = "../transferia-test-support" }

[lints]
workspace = true
