[package]
name = "transferia-provider-support"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
test = []

[dependencies]
anyhow.workspace = true
apache-avro.workspace = true
arrow.workspace = true
async-trait.workspace = true
base64.workspace = true
bigdecimal.workspace = true
bytes.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
flate2.workspace = true
futures-util.workspace = true
jsonpath_lib.workspace = true
jsonschema.workspace = true
itoa.workspace = true
prost.workspace = true
prost-reflect.workspace = true
protox.workspace = true
reqwest.workspace = true
rustls.workspace = true
rustls-native-certs.workspace = true
rustls-pemfile.workspace = true
ryu.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
simd-json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
time.workspace = true
tracing.workspace = true
transferia-core = { path = "../transferia-core" }
transferia-delivery-contracts = { path = "../transferia-delivery-contracts" }
transferia-registry = { path = "../transferia-registry" }

[dev-dependencies]
testcontainers.workspace = true
transferia-pipeline = { path = "../transferia-pipeline" }

[lints]
workspace = true
